apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  name: ftps-svc
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: active
      port: 21
      targetPort: 21
    - protocol: TCP
      name: passive
      port: 2142
      targetPort: 2142
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: active
        - containerPort: 2142
          name: passive